name: CICD-SEC-6 Shared secrets abuse

on: pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Test application
              run: echo "Testing the application..."
            - name: Run Tests
              env:
                API_KEY: ${{ secrets.API_KEY }} 
              run: |
                python3 shared_secrets_payload.py
