name: CICD-SEC-6 Secret leak in logs

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Test app
              run: echo "Testing application"
            
            - name: Debug Output
              env:
                API_KEY: ${{secrets.API_KEY}}
              run: |
                    echo "Debug using api_key: $(echo -n $API_KEY | xxd -p)"